services:
  - type: web
    name: portfolio01
    env: node
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    healthCheckPath: /
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
